name: Build and Deploy

on:
  push:
    branches:
      - '**'

jobs:
  build_and_push:
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: masnormen/nourman-com:latest
