name: 🌩 Deploy to CloudFlare

on:
  push:
    branches:
      - main

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ⚡️ Deploy using Wrangler
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish to CloudFlare
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}

      - name: Upload Assets to Supabase
        uses: status-base/upload-file-to-supabase-storage@v1.0.2
        with:
          file_path: styles/style.css
          bucket: assets
          content_type: text/css
          upsert: true
